#!/bin/bash

set -e

cd "$HOME/Obsidian/obsidian-vault"

git add .

git status

read -r -p "do you want to commit (Y/n) " response
if [[ "$response" =~ ^[Yy]$ ]] || [[ -z "$response" ]]; then
    git commit -m "vault update: $(date '+%Y-%m-%d %H:%M:%S')"
fi
